// <auto-generated />

using EffectiveWorker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EffectiveWorker.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EffectiveWorker.model.Project", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<int>("Premium");

                b.Property<int>("WorkerId");

                b.HasKey("Id");

                b.HasIndex("WorkerId");

                b.ToTable("Projects");
            });

            modelBuilder.Entity("EffectiveWorker.model.Worker", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<string>("Patronimic");

                b.Property<string>("Surname");

                b.HasKey("Id");

                b.ToTable("Workers");
            });

            modelBuilder.Entity("EffectiveWorker.model.Project", b =>
            {
                b.HasOne("EffectiveWorker.model.Worker", "Worker")
                    .WithMany("Projects")
                    .HasForeignKey("WorkerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}